name: SonyLiv Playlist Update

on:
  workflow_dispatch:

  schedule:
    # প্রতি ২ ঘণ্টা পর রান হবে
    - cron: "0 */2 * * *"

permissions:
  contents: write

concurrency:
  group: sonyliv-playlist
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python Script
        run: |
          python test.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add sonyLiv_playlist.m3u sonyLiv_data.json

          if git diff --cached --quiet; then
            echo "No changes detected."
            exit 0
          fi

          git commit -m "Auto update SonyLiv playlist"
          git push
